### ISSUE TITLE
Help with styling sticker order fields

### ISSUE THREAD

**Issue by chreriksen** [LeieTing/ghost-theme#2]
I could use some help with styling the sticker order fields. 

Doesn't need to be fancy, just more spacing between the input text and the field itself. And `Postnummer` and `Sted` on the same line, with about 30/70 balance? 

http://blogg.leieting.no/klistremerker/

**Comment by chreriksen** [comment]
Post is now changed to draft until we are ready to publish it.

http://blogg.leieting.no/p/dae9836b-03f3-4145-815f-42967708dc2c/

**Comment by kimroen** [comment]
This got some love by the recent casper upgrade:

![skjermbilde 2016-06-01 kl 21 09 26](https://cloud.githubusercontent.com/assets/520420/15722296/4a319074-283d-11e6-956b-bb6924648a4c.png)

**Comment by chreriksen** [comment]
Nice.

**Comment by kimroen** [comment]
In progress
<img width="748" alt="bestill" src="https://cloud.githubusercontent.com/assets/520420/15757539/473c3f94-2906-11e6-85b1-f335290b13fd.png">
