### ISSUE TITLE
Custom image tag so it doesn't go edge-to-edge on mobile screens

### ISSUE THREAD

**Issue by chreriksen** [LeieTing/ghost-theme#5]
Small images and logos look bad when scaled up on mobile devices because they are treated like any other image.

Could an idea be to create a custom image class that prevents the scaling? Just thinking out loud.

**Comment by kimroen** [comment]
Christer fixed this himself! be42bd72ae9835bb4c640e43052fc10f21b2dc15

**Comment by kimroen** [comment]
Christer fixed this himself! be42bd72ae9835bb4c640e43052fc10f21b2dc15
